vim.cmd([[ set encoding=utf8 ]])
vim.cmd([[ set expandtab ]])
vim.cmd([[ set number ]])
vim.cmd([[ set relativenumber ]])
vim.cmd([[ set shiftwidth=4 ]])
vim.cmd([[ set softtabstop=4 ]])
vim.cmd([[ set nocompatible ]])
vim.cmd([[ set showmatch ]])
vim.cmd([[ set smartcase ]])
vim.cmd([[ set hlsearch ]])
vim.cmd([[ set tabstop=4 ]])
vim.cmd([[ set cc=120 ]])
vim.cmd([[ filetype plugin indent on ]])
vim.cmd([[ syntax on]])
vim.cmd([[ set noswapfile ]])

vim.cmd([[ set bg=dark ]])
vim.cmd([[ set termguicolors ]])
vim.cmd([[ colorscheme onedark]])
